#!/usr/bin/env bash
# Tencent is pleased to support the open source community by making BK-BASE 蓝鲸基础平台 available.
#
# Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
#
# BK-BASE 蓝鲸基础平台 is licensed under the MIT License.
#
# License for BK-BASE 蓝鲸基础平台:
# --------------------------------------------------------------------
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
# LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
# NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.


source "$HOME"/.bkrc
source "$CTRL_DIR"/utils.fc
workon bkdata-metaapi
echo "now env: [$BKDATA_VERSION_TYPE] $GEOG_AREA_CODE"
# open when new install; optional when upgrade
python manage.py shell -c 'from meta.utils.meta_sync import database_sync_to_meta;database_sync_to_meta()'
python manage.py shell -c "from meta.utils.meta_sync import sync_tags_to_meta;sync_tags_to_meta(platform='$BKDATA_VERSION_TYPE', geog='$GEOG_AREA_CODE')"
python manage.py shell -c "from meta.utils.meta_sync import init_default_cluster_group;init_default_cluster_group(platform='$BKDATA_VERSION_TYPE', geog='$GEOG_AREA_CODE', multi_geog=$MULTI_GEOG_AREA)"
