# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-BASE 蓝鲸基础计算平台 available.
Copyright (C) 2019 THL A29 Limited, a Tencent company. All rights reserved.
Licensed under the MIT License (the "License"); you may not use this file except in compliance with the License.
You may obtain a copy of the License at http://opensource.org/licenses/MIT
Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and limitations under the License.
"""
# Generated by Django 1.11.23 on 2021-01-19 03:04


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_control", "0003_auto_20200814_2238"),
    ]

    operations = [
        migrations.AlterField(
            model_name="functioncontroller",
            name="service_module",
            field=models.CharField(
                blank=True,
                choices=[
                    ("datahub", "datahub"),
                    ("dataflow", "dataflow"),
                    ("modelflow", "modelflow"),
                    ("datamart", "datamart"),
                    ("datamodeling", "datamodeling"),
                    ("datalab", "datalab"),
                ],
                help_text="\u6bd4\u5982 datahub/dataflow/...",
                max_length=64,
                null=True,
                verbose_name="\u670d\u52a1\u6a21\u5757",
            ),
        ),
    ]
