web: gunicorn wsgi -w 4 -k gevent -b :$PORT --access-logfile - --error-logfile - --access-logformat '[%(h)s] %({request_id}i)s %(u)s %(t)s "%(r)s" %(s)s %(D)s %(b)s "%(f)s" "%(a)s"'
worker: export C_FORCE_ROOT="true" && python manage.py celery worker -l info
beat: python manage.py celery beat -l info
