# Tencent is pleased to support the open source community by making BK-BASE 蓝鲸基础平台 available.
#
# Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.
#
# BK-BASE 蓝鲸基础平台 is licensed under the MIT License.
#
# License for BK-BASE 蓝鲸基础平台:
# --------------------------------------------------------------------
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
# LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
# NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

custom: {}

hub:
  service:
    type: ClusterIP
    annotations: {}
    ports:
      nodePort:
    loadBalancerIP:
  baseUrl: /
  cookieSecret:
  publicURL:
  initContainers: []
  uid: 1000
  fsGid: 1000
  nodeSelector: {}
  concurrentSpawnLimit: 64
  consecutiveFailureLimit: 5
  activeServerLimit:
  deploymentStrategy:
    ## type: Recreate
    ## - sqlite-pvc backed hubs require the Recreate deployment strategy as a
    ##   typical PVC storage can only be bound to one pod at the time.
    ## - JupyterHub isn't designed to support being run in parallell. More work
    ##   needs to be done in JupyterHub itself for a fully highly available (HA)
    ##   deployment of JupyterHub on k8s is to be possible.
    type: Recreate
  db:
    type: mysql
    upgrade:
    pvc:
      annotations: {}
      selector: {}
      accessModes:
        - ReadWriteOnce
      storage: 1Gi
      subPath:
      storageClassName:
    url: 'mysql+mysqlconnector://__MYSQL_DATALAB_USER__:__MYSQL_DATALAB_PASS__@__MYSQL_DATALAB_IP0__:__MYSQL_DATALAB_PORT__/bkdata_jupyterhub'
    password:
  labels: {}
  annotations: {}
  extraConfig:  
    nbvalues: |
      c.KubeSpawner.environment.update({
        'QUERYENGINE_API_HOST': '__BKDATA_QUERYENGINEAPI_HOST__',
      	'QUERYENGINE_API_PORT': '__BKDATA_QUERYENGINEAPI_PORT__',
      	'AUTH_API_HOST': '__BKDATA_AUTHAPI_HOST__',
      	'AUTH_API_PORT': '__BKDATA_AUTHAPI_PORT__',
        'META_API_HOST': '__BKDATA_METAAPI_HOST__',
        'META_API_PORT': '__BKDATA_METAAPI_PORT__',
      	'DATALAB_API_HOST': '__BKDATA_DATALABAPI_HOST__',
      	'DATALAB_API_PORT': '__BKDATA_DATALABAPI_PORT__',
        'DATAFLOW_API_HOST': '__BKDATA_DATAFLOWAPI_HOST__',
        'DATAFLOW_API_PORT': '__BKDATA_DATAFLOWAPI_PORT__',
        'DATAHUB_API_HOST': '__BKDATA_DATAHUBAPI_HOST__',
        'DATAHUB_API_PORT': '__BKDATA_DATAHUBAPI_PORT__',
      	'BK_LOCALE': '__BKDATA_LANGUAGE__',
        'BK_DOC_URL': '__HTTP_SCHEMA__://__BKDATA_DOC_URL__/',
        'BK_RUN_VERSION': '__BKDATA_WEB_RUN_VERSION__',
        'BK_APP_CODE': '__BKDATA_WEB_APP_CODE__',
        'DATALAB_PROJECT': '__BKDATA_DATALAB_DEFAULT_PROJECT__'
      })
  extraConfigMap: {}
  extraEnv: {}
  extraContainers: []
  extraVolumes: []
  extraVolumeMounts: []
  image:
    name: __BKDATA_IMAGE_REPOSITORY__/datalab-jupyterhub
    tag: '4.0.0'
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - secretName
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
  services:
    myService:
      admin: true
      apiToken: '__BKDATA_JUPYTERHUB_ADMIN_TOKEN__'
  imagePullSecret:
    enabled: false
    registry:
    username:
    email:
    password:
  pdb:
    enabled: true
    minAvailable: 1
  networkPolicy:
    enabled: false
    ingress: []
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
  allowNamedServers: false
  namedServerLimitPerUser:
  authenticatePrometheus:
  redirectToServer:
  shutdownOnLogout:
  templatePaths: []
  templateVars: {}
  livenessProbe:
    enabled: false
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    enabled: true
    initialDelaySeconds: 0
    periodSeconds: 10
  # existingSecret: existing-secret

rbac:
  enabled: true


proxy:
  secretToken: '__BKDATA_JUPYTERHUB_PROXY_TOKEN__'
  deploymentStrategy:
    ## type: Recreate
    ## - JupyterHub's interaction with the CHP proxy becomes a lot more robust
    ##   with this configuration. To understand this, consider that JupyterHub
    ##   during startup will interact a lot with the k8s service to reach a
    ##   ready proxy pod. If the hub pod during a helm upgrade is restarting
    ##   directly while the proxy pod is making a rolling upgrade, the hub pod
    ##   could end up running a sequence of interactions with the old proxy pod
    ##   and finishing up the sequence of interactions with the new proxy pod.
    ##   As CHP proxy pods carry individual state this is very error prone. One
    ##   outcome when not using Recreate as a strategy has been that user pods
    ##   have been deleted by the hub pod because it considered them unreachable
    ##   as it only configured the old proxy pod but not the new before trying
    ##   to reach them.
    type: Recreate
    ## rollingUpdate:
    ## - WARNING:
    ##   This is required to be set explicitly blank! Without it being
    ##   explicitly blank, k8s will let eventual old values under rollingUpdate
    ##   remain and then the Deployment becomes invalid and a helm upgrade would
    ##   fail with an error like this:
    ##
    ##     UPGRADE FAILED
    ##     Error: Deployment.apps "proxy" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
    ##     Error: UPGRADE FAILED: Deployment.apps "proxy" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
    rollingUpdate:
  service:
    type: NodePort
    labels: {}
    annotations: {}
    nodePorts:
      http:
      https:
    loadBalancerIP:
    loadBalancerSourceRanges: []
  chp:
    image:
      name: jupyterhub/configurable-http-proxy
      tag: 4.2.0
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
    readinessProbe:
      enabled: true
      initialDelaySeconds: 0
      periodSeconds: 10
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
  nginx:
    image:
      name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
      tag: 0.15.0
    proxyBodySize: 64m
    hstsIncludeSubdomains: 'false'
    resources: {}
  lego:
    image:
      name: jetstack/kube-lego
      tag: 0.1.7
    resources: {}
  labels: {}
  nodeSelector: {}
  pdb:
    enabled: true
    minAvailable: 1
  https:
    enabled: true
    type: letsencrypt
    #type: letsencrypt, manual, offload, secret
    letsencrypt:
      contactEmail: ''
    manual:
      key:
      cert:
    secret:
      name: ''
      key: tls.key
      crt: tls.crt
    hosts: []
  networkPolicy:
    enabled: false
    ingress: []
    egress:
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0


auth:
  type: dummy
  whitelist:
    users:
  admin:
    access: true
    users:
      - __BKDATA_JUPYTERHUB_ADMIN_USER__
  dummy:
    password:
  ldap:
    dn:
      search: {}
      user: {}
    user: {}
  state:
    enabled: false
    cryptoKey:


singleuser:
  extraTolerations: []
  nodeSelector: {}
  extraNodeAffinity:
    required: []
    preferred: []
  extraPodAffinity:
    required: []
    preferred: []
  extraPodAntiAffinity:
    required: []
    preferred: []
  networkTools:
    image:
      name: jupyterhub/k8s-network-tools
      tag: '1.0.0'
  cloudMetadata:
    enabled: false
    ip: 169.254.169.254 # 保留ip，与环境无关
  networkPolicy:
    enabled: false
    ingress: []
    egress:
    # Required egress is handled by other rules so it's safe to modify this
      - to:
          - ipBlock:
              cidr: 0.0.0.0/0
              except:
                - 169.254.169.254/32
  events: true
  extraAnnotations: {}
  extraLabels:
    hub.jupyter.org/network-access-hub: 'true'
  extraEnv: 
    EDITOR: "vim"
  lifecycleHooks: 
  initContainers: []
  extraContainers: []
  uid: 0
  fsGid: 0
  serviceAccountName:
  image:
    name: __BKDATA_IMAGE_REPOSITORY__/datalab-jupyter-notebook
    tag: '4.0.0'
    pullPolicy: IfNotPresent
    # pullSecrets:
    #   - secretName
  imagePullSecret:
    enabled: false
    registry:
    username:
    email:
    password:
  startTimeout: 300
  cpu:
    limit: 4
    guarantee: 0.05
  memory:
    limit: 8G
    guarantee: 512M
  extraResource:
    limits: {}
    guarantees: {}
  cmd: jupyterhub-singleuser
  defaultUrl:
  extraPodConfig: {}


scheduling:
  userScheduler:
    enabled: false
    replicas: 2
    logLevel: 4
    ## policy:
    ## Allows you to provide custom YAML/JSON to render into a JSON policy.cfg,
    ## a configuration file for the kube-scheduler binary.
    ## NOTE: The kube-scheduler binary in the kube-scheduler image we are
    ## currently using may be version bumped. It would for example happen if we
    ## increase the lowest supported k8s version for the helm chart. At this
    ## point, the provided policy.cfg may require a change along with that due
    ## to breaking changes in the kube-scheduler binary.
    policy: {}
    image:
      name: gcr.io/google_containers/kube-scheduler-amd64
      tag: v1.13.12
    nodeSelector: {}
    pdb:
      enabled: true
      minAvailable: 1
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
  podPriority:
    enabled: false
    globalDefault: false
    defaultPriority: 0
    userPlaceholderPriority: -10
  userPlaceholder:
    enabled: true
    replicas: 0
  corePods:
    nodeAffinity:
      matchNodePurpose: prefer
  userPods:
    nodeAffinity:
      matchNodePurpose: prefer


prePuller:
  hook:
    enabled: false
    image:
      name: jupyterhub/k8s-image-awaiter
      tag: '1.0.0'
  continuous:
    enabled: false
  extraImages: {}
  pause:
    image:
      name: gcr.azk8s.cn/google_containers/pause
      tag: '3.1'


ingress:
  enabled: true
  annotations: {kubernetes.io/ingress.class: nginx}
  hosts: ['__BKDATA_JUPYTERHUBWEB_FQDN__']
  pathSuffix: ''
  tls:
  - hosts: ['__BKDATA_JUPYTERHUBWEB_FQDN__']
    secretName: bkdata-cert


cull:
  enabled: true
  users: false
  timeout: 14400
  every: 2400
  concurrency: 10
  maxAge: 0


debug:
  enabled: false
