.PHONY: clean build

all: build

clean:
	rm .gitlab-ci.yml
	rm .pre-commit-config.yaml
	rm .flake8
	rm -rf ./contents
	rm -rf ./tests/bin
	rm ./tests/dataapi_settings.py
	rm ./tests/dataapi_settings_pro.py
	rm -rf ./extend