[
    {
        "change_time": "2020-08-11 17:24:00",
        "changed_data": "{\"project_id\": 6, \"project_name\": \"\\u6570\\u636e\\u4e2d\\u53f0\\u8fd0\\u8425\\u6570\\u636e\", \"active\": 1, \"bk_app_code\": \"data\", \"created_by\": \"admin\", \"created_at\": \"2020-08-11 16:44:55\", \"updated_by\": null, \"updated_at\": null, \"deleted_by\": null, \"deleted_at\": null, \"description\": \"IEG\\u6570\\u636e\\u4e2d\\u53f0\\u8fd0\\u8425\\u6570\\u636e\"}",
        "db_name": "bkdata_basic",
        "method": "CREATE",
        "primary_key_value": 6,
        "table_name": "project_info"
    }
]