[
    {
        "change_time": "2021-05-26 17:24:00",
        "changed_data": "{\"project_id\": 6, \"project_name\": \"Demo\", \"active\": 1, \"bk_app_code\": \"data\", \"created_by\": \"admin\", \"created_at\": \"2021-05-26 17:24:00\", \"updated_by\": null, \"updated_at\": null, \"deleted_by\": null, \"deleted_at\": null, \"description\": \"\\u8ba1\\u7b97\\u5e73\\u53f0Demo\"}",
        "db_name": "bkdata_basic",
        "method": "UPDATE",
        "primary_key_value": 6,
        "table_name": "project_info"
    }
]