[tool.black]
line-length = 120
include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.pytest.ini_options]
log_cli = true
testpaths = ["tests"]
addopts="--cov-report=term --junitxml=reports/coverage/cov.xml --cov-report=html --reuse-db --cov=."
