# -*- coding: utf-8 -*
"""
Tencent is pleased to support the open source community by making BK-BASE 蓝鲸基础平台 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-BASE 蓝鲸基础平台 is licensed under the MIT License.

License for BK-BASE 蓝鲸基础平台:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""
# flake8: noqa

# [公共] API 启动环境
RUN_VERSION = "__BKDATA_RUN_VERSION__"
RUN_MODE = "__BKDATA_RUN_MODE__"
APP_NAME = "codecheck"

# [专属] 项目部署相关信息
BIND_IP_ADDRESS = "__BKDATA_CODECHECKAPI_HOST__"
pizza_port = __BKDATA_CODECHECKAPI_PORT__

# [公共] 其他模块API参数
AUTH_API_HOST = "__BKDATA_AUTHAPI_HOST__"
AUTH_API_PORT = __BKDATA_AUTHAPI_PORT__
ACCESS_API_HOST = "__BKDATA_DATAHUBAPI_HOST__"
ACCESS_API_PORT = __BKDATA_DATAHUBAPI_PORT__
DATABUS_API_HOST = "__BKDATA_DATAHUBAPI_HOST__"
DATABUS_API_PORT = __BKDATA_DATAHUBAPI_PORT__
DATAFLOW_API_HOST = "__BKDATA_DATAFLOWAPI_HOST__"
DATAFLOW_API_PORT = __BKDATA_DATAFLOWAPI_PORT__
DATAMANAGE_API_HOST = "__BKDATA_DATAMANAGEAPI_HOST__"
DATAMANAGE_API_PORT = __BKDATA_DATAMANAGEAPI_PORT__
DATAQUERY_API_HOST = "__BKDATA_QUERYENGINEAPI_HOST__"
DATAQUERY_API_PORT = __BKDATA_QUERYENGINEAPI_PORT__
JOBNAVI_API_HOST = "__BKDATA_JOBNAVIAPI_HOST__"
JOBNAVI_API_PORT = __BKDATA_JOBNAVIAPI_PORT__
META_API_HOST = "__BKDATA_METAAPI_HOST__"
META_API_PORT = __BKDATA_METAAPI_PORT__
STOREKIT_API_HOST = "__BKDATA_DATAHUBAPI_HOST__"
STOREKIT_API_PORT = __BKDATA_DATAHUBAPI_PORT__
MODELFLOW_API_HOST = "__BKDATA_MODELFLOWAPI_HOST__"
MODELFLOW_API_PORT = __BKDATA_MODELFLOWAPI_PORT__
AIOPS_API_HOST = "__BKDATA_AIOPSAPI_HOST__"
AIOPS_API_PORT = __BKDATA_AIOPSAPI_PORT__
MODEL_API_HOST = "__BKDATA_MODELAPI_HOST__"
MODEL_API_PORT = __BKDATA_MODELAPI_PORT__
RESOURCECENTER_API_HOST = "__BKDATA_RESOURCECENTER_API_HOST__"
RESOURCECENTER_API_PORT = __BKDATA_RESOURCECENTER_API_PORT__
CODECHECK_API_HOST = "__BKDATA_CODECHECKAPI_HOST__"
CODECHECK_API_PORT = __BKDATA_CODECHECKAPI_PORT__
BASE_DATALAB_URL_API_HOST = "__BKDATA_DATALABAPI_HOST__"
BASE_DATALAB_URL_API_PORT = __BKDATA_DATALABAPI_PORT__
BKSQL_MLSQL_HOST = "__BKDATA_MLSQL_API_HOST__"
BKSQL_MLSQL_PORT = __BKDATA_MLSQL_API_PORT__
API_URL = "__BKDATA_DATAFLOWAPI_HOST__:__BKDATA_DATAFLOWAPI_PORT__"

# [公共] 第三方系统 URL
CC_API_URL = "http://__PAAS_FQDN__/component/compapi/cc/"
JOB_API_URL = "http://__PAAS_FQDN__/component/compapi/job/"
TOF_API_URL = "http://__PAAS_FQDN__/component/compapi/tof/"
SMCS_API_URL = "http://__PAAS_FQDN__/component/compapi/smcs/"
GSE_API_URL = "http://__PAAS_FQDN__/component/compapi/gse/"
CMSI_API_URL = "http://__PAAS_FQDN__/component/compapi/cmsi/"
BK_LOGIN_API_URL = "http://__PAAS_HOST__:__PAAS_HTTP_PORT__/api/c/compapi/v2/bk_login/"

# [公共] 运行时区设置
TIME_ZONE = "__BK_TIMEZONE__"
DATA_TIME_ZONE = "__GEOG_AREA_TIMEZONE__"
UC_TIME_ZONE = "__GEOG_AREA_TIMEZONE__"

# PaaS注册之后生成的APP_ID, APP_TOKEN, BK_PAAS_HOST
APP_ID = "__APP_CODE__"
APP_TOKEN = "__APP_TOKEN__"
BK_PAAS_HOST = "http://__PAAS_HOST__:__PAAS_HTTP_PORT__"
SECRET_KEY = "__DJANGO_SECRET_KEY__"

# [公共] 加解密配置
CRYPT_INSTANCE_KEY = "__CRYPT_INSTANCE_KEY__"

# 数据开发
CODECHECK_DB_HOST = "__MYSQL_IP0__"
CODECHECK_DB_PORT = __MYSQL_PORT__
CODECHECK_DB_USER = "__MYSQL_USER__"
CODECHECK_DB_PASSWORD = "__MYSQL_PASS__"

CODE_CHECK_SERVER_ADDR = "__CODECHECK_SERVER_HOST__:__CODECHECK_SERVER_PORT__"
