# -*- coding: utf-8 -*-
"""
Tencent is pleased to support the open source community by making BK-BASE 蓝鲸基础平台 available.

Copyright (C) 2021 THL A29 Limited, a Tencent company.  All rights reserved.

BK-BASE 蓝鲸基础平台 is licensed under the MIT License.

License for BK-BASE 蓝鲸基础平台:
--------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial
portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN
NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
"""

# [公共] API 启动环境
RUN_VERSION = "__BKDATA_RUN_VERSION__"
RUN_MODE = "__BKDATA_RUN_MODE__"

# [专属] 项目部署相关信息
pizza_port = __BKDATA_DATALABAPI_PORT__
BIND_IP_ADDRESS = "__BKDATA_DATALABAPI_HOST__"
APP_NAME = 'datalab'

# [公共] 其他模块 API 参数
AUTH_API_HOST = "__BKDATA_AUTHAPI_HOST__"
AUTH_API_PORT = __BKDATA_AUTHAPI_PORT__
ACCESS_API_HOST = "__BKDATA_DATAHUBAPI_HOST__"
ACCESS_API_PORT = __BKDATA_DATAHUBAPI_PORT__
DATABUS_API_HOST = "__BKDATA_DATAHUBAPI_HOST__"
DATABUS_API_PORT = __BKDATA_DATAHUBAPI_PORT__
DATAFLOW_API_HOST = "__BKDATA_DATAFLOWAPI_HOST__"
DATAFLOW_API_PORT = __BKDATA_DATAFLOWAPI_PORT__
DATAMANAGE_API_HOST = "__BKDATA_DATAMANAGEAPI_HOST__"
DATAMANAGE_API_PORT = __BKDATA_DATAMANAGEAPI_PORT__
DATAQUERY_API_HOST = "__BKDATA_DATAQUERYAPI_HOST__"
DATAQUERY_API_PORT = __BKDATA_DATAQUERYAPI_PORT__
JOBNAVI_API_HOST = "__BKDATA_JOBNAVIAPI_HOST__"
JOBNAVI_API_PORT = __BKDATA_JOBNAVIAPI_PORT__
META_API_HOST = "__BKDATA_METAAPI_HOST__"
META_API_PORT = __BKDATA_METAAPI_PORT__
STOREKIT_API_HOST = "__BKDATA_DATAHUBAPI_HOST__"
STOREKIT_API_PORT = __BKDATA_DATAHUBAPI_PORT__
QUERYENGINE_API_HOST = "__BKDATA_QUERYENGINEAPI_HOST__"
QUERYENGINE_API_PORT = __BKDATA_QUERYENGINEAPI_PORT__
JUPYTERHUB_API_HOST = "__BKDATA_JUPYTERHUBAPI_HOST__"
JUPYTERHUB_API_PORT = __BKDATA_JUPYTERHUBAPI_PORT__
# web域名
QUERYENGINEWEB_FQDN = "__BKDATA_QUERYENGINEWEB_FQDN__"
JUPYTERHUBWEB_FQDN = "__BKDATA_JUPYTERHUBWEB_FQDN__"

# 笔记产出物类型
OUTPUT_TYPES = __BKDATA_DATALAB_OUTPUT_TYPES__

# 创建结果表时支持关联的存储类型
SUPPORT_ASSOCIATED_STORAGE = __BKDATA_DATALAB_SUPPORT_ASSOCIATED_STORAGE__

# 平台hdfs默认存储格式
HDFS_DATA_TYPE = "__BKDATA_DATALAB_HDFS_DATA_TYPE__"

# [公共] 运行时区设置
TIME_ZONE = '__BK_TIMEZONE__'

# [公共] http/https
HTTP_SCHEMA = '__HTTP_SCHEMA__'

# 返回给前端的条数限制信息
RESULT_LIMIT = __BKDATA_DATALAB_RESULT_LIMIT__

# 查询任务目前支持的存储
AVAILABLE_STORAGE = __BKDATA_DATALAB_AVAILABLE_STORAGE__

# 数据探索对应的平台项目id，便于关联个人项目生成的rt、dp
DATALAB_PROJECT = __BKDATA_DATALAB_DEFAULT_PROJECT__

# 区域tag
DEFAULT_GEOG_AREA_TAG = "__DEFAULT_GEOG_AREA_TAG__"

# [公共] PaaS 注册之后生成的 APP_ID, APP_TOKEN, BK_PAAS_HOST
APP_ID = "__APP_CODE__"
APP_TOKEN = "__APP_TOKEN__"
BK_PAAS_HOST = "http://__PAAS_HOST__:__PAAS_HTTP_PORT__"
SECRET_KEY = "__APP_TOKEN__"

# [公共] 笔记ADMIN TOKEN
ADMIN_TOKEN = "__BKDATA_JUPYTERHUB_ADMIN_TOKEN__"

# [公共] 加解密配置
CRYPT_ROOT_KEY = "__BKDATA_ROOT_KEY__"
CRYPT_ROOT_IV = "__BKDATA_ROOT_IV__"
CRYPT_INSTANCE_KEY = "__CRYPT_INSTANCE_KEY__"

# MYSQL 配置
ANALYSIS_DB_HOST = "__MYSQL_DATALAB_IP0__"
ANALYSIS_DB_PORT = __MYSQL_DATALAB_PORT__
ANALYSIS_DB_USER = "__MYSQL_DATALAB_USER__"
ANALYSIS_DB_PASSWORD = "__MYSQL_DATALAB_PASS__"

